"""init: v0.1.0 release schema

Revision ID: 0001_init
Revises:
Create Date: 2026-04-19

首次公开发布的完整 schema。

本迁移由 `alembic revision --autogenerate` 从 `src/models.py` 的 SQLAlchemy
metadata 一次性生成,覆盖全部运行时所需的表 + 索引:

- 基础设施: users / devices / refresh_tokens / audit_logs / sync_cursors /
  sync_push_idempotency / attachment_files / backup_snapshots
- 账本 + 同步事件流: ledgers / sync_changes
- 用户偏好: user_profiles
- CQRS Q 端 projection(读路径): read_tx_projection / read_account_projection
  / read_category_projection / read_tag_projection / read_budget_projection

发布前把历史 20 个增量 migration 压平成这一个 —— 没有外部用户需要向前兼容,
压平后新部署一步到位,代码更易读,DB 初始化更快。
"""
from alembic import op
import sqlalchemy as sa


revision = '0001_init'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_is_admin'), 'users', ['is_admin'], unique=False)
    op.create_index(op.f('ix_users_is_enabled'), 'users', ['is_enabled'], unique=False)
    op.create_table('devices',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('app_version', sa.String(length=64), nullable=True),
    sa.Column('os_version', sa.String(length=64), nullable=True),
    sa.Column('device_model', sa.String(length=128), nullable=True),
    sa.Column('last_ip', sa.String(length=64), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_last_seen_at'), 'devices', ['last_seen_at'], unique=False)
    op.create_index(op.f('ix_devices_revoked_at'), 'devices', ['revoked_at'], unique=False)
    op.create_index(op.f('ix_devices_user_id'), 'devices', ['user_id'], unique=False)
    op.create_table('ledgers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('currency', sa.String(length=16), server_default='CNY', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'external_id', name='uq_ledgers_user_external')
    )
    op.create_index(op.f('ix_ledgers_external_id'), 'ledgers', ['external_id'], unique=False)
    op.create_index(op.f('ix_ledgers_user_id'), 'ledgers', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=True),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_device_id'), 'refresh_tokens', ['device_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('sync_cursors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('ledger_external_id', sa.String(length=128), nullable=False),
    sa.Column('last_cursor', sa.BigInteger(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'device_id', 'ledger_external_id', name='uq_sync_cursor')
    )
    op.create_index(op.f('ix_sync_cursors_device_id'), 'sync_cursors', ['device_id'], unique=False)
    op.create_index(op.f('ix_sync_cursors_ledger_external_id'), 'sync_cursors', ['ledger_external_id'], unique=False)
    op.create_index(op.f('ix_sync_cursors_user_id'), 'sync_cursors', ['user_id'], unique=False)
    op.create_table('sync_push_idempotency',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('device_id', sa.String(length=64), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('request_hash', sa.String(length=128), nullable=False),
    sa.Column('response_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'device_id', 'idempotency_key', name='uq_sync_push_idempotency')
    )
    op.create_index(op.f('ix_sync_push_idempotency_device_id'), 'sync_push_idempotency', ['device_id'], unique=False)
    op.create_index(op.f('ix_sync_push_idempotency_expires_at'), 'sync_push_idempotency', ['expires_at'], unique=False)
    op.create_index(op.f('ix_sync_push_idempotency_idempotency_key'), 'sync_push_idempotency', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_sync_push_idempotency_user_id'), 'sync_push_idempotency', ['user_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=True),
    sa.Column('avatar_file_id', sa.String(length=128), nullable=True),
    sa.Column('avatar_version', sa.Integer(), nullable=False),
    sa.Column('income_is_red', sa.Boolean(), nullable=True),
    sa.Column('theme_primary_color', sa.String(length=7), nullable=True),
    sa.Column('appearance_json', sa.Text(), nullable=True),
    sa.Column('ai_config_json', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True)
    op.create_table('attachment_files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ledger_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ledger_id'], ['ledgers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_attachment_files_ledger_created', 'attachment_files', ['ledger_id', 'created_at'], unique=False)
    op.create_index('idx_attachment_files_sha256', 'attachment_files', ['sha256'], unique=False)
    op.create_index(op.f('ix_attachment_files_created_at'), 'attachment_files', ['created_at'], unique=False)
    op.create_index(op.f('ix_attachment_files_ledger_id'), 'attachment_files', ['ledger_id'], unique=False)
    op.create_index(op.f('ix_attachment_files_sha256'), 'attachment_files', ['sha256'], unique=False)
    op.create_index(op.f('ix_attachment_files_user_id'), 'attachment_files', ['user_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('ledger_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=128), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ledger_id'], ['ledgers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_ledger_id'), 'audit_logs', ['ledger_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('backup_artifacts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('ledger_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ledger_id'], ['ledgers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_backup_artifacts_ledger_created', 'backup_artifacts', ['ledger_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_backup_artifacts_checksum_sha256'), 'backup_artifacts', ['checksum_sha256'], unique=False)
    op.create_index(op.f('ix_backup_artifacts_created_at'), 'backup_artifacts', ['created_at'], unique=False)
    op.create_index(op.f('ix_backup_artifacts_kind'), 'backup_artifacts', ['kind'], unique=False)
    op.create_index(op.f('ix_backup_artifacts_ledger_id'), 'backup_artifacts', ['ledger_id'], unique=False)
    op.create_index(op.f('ix_backup_artifacts_user_id'), 'backup_artifacts', ['user_id'], unique=False)
    op.create_table('backup_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('ledger_id', sa.String(length=36), nullable=False),
    sa.Column('snapshot_json', sa.Text(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ledger_id'], ['ledgers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backup_snapshots_ledger_id'), 'backup_snapshots', ['ledger_id'], unique=False)
    op.create_index(op.f('ix_backup_snapshots_user_id'), 'backup_snapshots', ['user_id'], unique=False)
    op.create_table('read_account_projection',
    sa.Column('ledger_id', sa.String(length=36), nullable=False),
    sa.Column('sync_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('account_type', sa.String(length=64), nullable=True),
    sa.Column('currency', sa.String(length=16), nullable=True),
    sa.Column('initial_balance', sa.Float(), nullable=True),
    sa.Column('source_change_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['ledger_id'], ['ledgers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ledger_id', 'sync_id')
    )
    op.create_index(op.f('ix_read_account_projection_user_id'), 'read_account_projection', ['user_id'], unique=False)
    op.create_table('read_budget_projection',
    sa.Column('ledger_id', sa.String(length=36), nullable=False),
    sa.Column('sync_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('budget_type', sa.String(length=32), nullable=True),
    sa.Column('category_sync_id', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('period', sa.String(length=32), nullable=True),
    sa.Column('start_day', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('source_change_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['ledger_id'], ['ledgers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ledger_id', 'sync_id')
    )
    op.create_index('ix_read_budget_ledger_cat', 'read_budget_projection', ['ledger_id', 'category_sync_id'], unique=False)
    op.create_index(op.f('ix_read_budget_projection_user_id'), 'read_budget_projection', ['user_id'], unique=False)
    op.create_table('read_category_projection',
    sa.Column('ledger_id', sa.String(length=36), nullable=False),
    sa.Column('sync_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('kind', sa.String(length=32), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('icon', sa.String(length=255), nullable=True),
    sa.Column('icon_type', sa.String(length=32), nullable=True),
    sa.Column('custom_icon_path', sa.String(length=1024), nullable=True),
    sa.Column('icon_cloud_file_id', sa.String(length=36), nullable=True),
    sa.Column('icon_cloud_sha256', sa.String(length=64), nullable=True),
    sa.Column('parent_name', sa.Text(), nullable=True),
    sa.Column('source_change_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['ledger_id'], ['ledgers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ledger_id', 'sync_id')
    )
    op.create_index('ix_read_cat_ledger_kind', 'read_category_projection', ['ledger_id', 'kind'], unique=False)
    op.create_index(op.f('ix_read_category_projection_user_id'), 'read_category_projection', ['user_id'], unique=False)
    op.create_table('read_tag_projection',
    sa.Column('ledger_id', sa.String(length=36), nullable=False),
    sa.Column('sync_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=32), nullable=True),
    sa.Column('source_change_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['ledger_id'], ['ledgers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ledger_id', 'sync_id')
    )
    op.create_index(op.f('ix_read_tag_projection_user_id'), 'read_tag_projection', ['user_id'], unique=False)
    op.create_table('read_tx_projection',
    sa.Column('ledger_id', sa.String(length=36), nullable=False),
    sa.Column('sync_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('tx_type', sa.String(length=16), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('happened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('category_sync_id', sa.String(length=255), nullable=True),
    sa.Column('category_name', sa.Text(), nullable=True),
    sa.Column('category_kind', sa.String(length=32), nullable=True),
    sa.Column('account_sync_id', sa.String(length=255), nullable=True),
    sa.Column('account_name', sa.Text(), nullable=True),
    sa.Column('from_account_sync_id', sa.String(length=255), nullable=True),
    sa.Column('from_account_name', sa.Text(), nullable=True),
    sa.Column('to_account_sync_id', sa.String(length=255), nullable=True),
    sa.Column('to_account_name', sa.Text(), nullable=True),
    sa.Column('tags_csv', sa.Text(), nullable=True),
    sa.Column('tag_sync_ids_json', sa.Text(), nullable=True),
    sa.Column('attachments_json', sa.Text(), nullable=True),
    sa.Column('tx_index', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('source_change_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['ledger_id'], ['ledgers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ledger_id', 'sync_id')
    )
    op.create_index('ix_read_tx_ledger_account', 'read_tx_projection', ['ledger_id', 'account_sync_id'], unique=False)
    op.create_index('ix_read_tx_ledger_category', 'read_tx_projection', ['ledger_id', 'category_sync_id'], unique=False)
    op.create_index('ix_read_tx_ledger_time', 'read_tx_projection', ['ledger_id', sa.literal_column('happened_at DESC'), sa.literal_column('tx_index DESC')], unique=False)
    op.create_index(op.f('ix_read_tx_projection_user_id'), 'read_tx_projection', ['user_id'], unique=False)
    op.create_index('ix_read_tx_user_time', 'read_tx_projection', ['user_id', sa.literal_column('happened_at DESC')], unique=False)
    op.create_table('sync_changes',
    sa.Column('change_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('ledger_id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_sync_id', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_by_device_id', sa.String(length=36), nullable=True),
    sa.Column('updated_by_user_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['ledger_id'], ['ledgers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('change_id')
    )
    op.create_index('idx_sync_changes_entity_latest', 'sync_changes', ['ledger_id', 'entity_type', 'entity_sync_id', 'change_id'], unique=False)
    op.create_index('idx_sync_changes_ledger_cursor', 'sync_changes', ['ledger_id', 'change_id'], unique=False)
    op.create_index('idx_sync_changes_user_cursor', 'sync_changes', ['user_id', 'change_id'], unique=False)
    op.create_index(op.f('ix_sync_changes_action'), 'sync_changes', ['action'], unique=False)
    op.create_index(op.f('ix_sync_changes_entity_sync_id'), 'sync_changes', ['entity_sync_id'], unique=False)
    op.create_index(op.f('ix_sync_changes_entity_type'), 'sync_changes', ['entity_type'], unique=False)
    op.create_index(op.f('ix_sync_changes_ledger_id'), 'sync_changes', ['ledger_id'], unique=False)
    op.create_index(op.f('ix_sync_changes_updated_at'), 'sync_changes', ['updated_at'], unique=False)
    op.create_index(op.f('ix_sync_changes_updated_by_device_id'), 'sync_changes', ['updated_by_device_id'], unique=False)
    op.create_index(op.f('ix_sync_changes_updated_by_user_id'), 'sync_changes', ['updated_by_user_id'], unique=False)
    op.create_index(op.f('ix_sync_changes_user_id'), 'sync_changes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sync_changes_user_id'), table_name='sync_changes')
    op.drop_index(op.f('ix_sync_changes_updated_by_user_id'), table_name='sync_changes')
    op.drop_index(op.f('ix_sync_changes_updated_by_device_id'), table_name='sync_changes')
    op.drop_index(op.f('ix_sync_changes_updated_at'), table_name='sync_changes')
    op.drop_index(op.f('ix_sync_changes_ledger_id'), table_name='sync_changes')
    op.drop_index(op.f('ix_sync_changes_entity_type'), table_name='sync_changes')
    op.drop_index(op.f('ix_sync_changes_entity_sync_id'), table_name='sync_changes')
    op.drop_index(op.f('ix_sync_changes_action'), table_name='sync_changes')
    op.drop_index('idx_sync_changes_user_cursor', table_name='sync_changes')
    op.drop_index('idx_sync_changes_ledger_cursor', table_name='sync_changes')
    op.drop_index('idx_sync_changes_entity_latest', table_name='sync_changes')
    op.drop_table('sync_changes')
    op.drop_index('ix_read_tx_user_time', table_name='read_tx_projection')
    op.drop_index(op.f('ix_read_tx_projection_user_id'), table_name='read_tx_projection')
    op.drop_index('ix_read_tx_ledger_time', table_name='read_tx_projection')
    op.drop_index('ix_read_tx_ledger_category', table_name='read_tx_projection')
    op.drop_index('ix_read_tx_ledger_account', table_name='read_tx_projection')
    op.drop_table('read_tx_projection')
    op.drop_index(op.f('ix_read_tag_projection_user_id'), table_name='read_tag_projection')
    op.drop_table('read_tag_projection')
    op.drop_index(op.f('ix_read_category_projection_user_id'), table_name='read_category_projection')
    op.drop_index('ix_read_cat_ledger_kind', table_name='read_category_projection')
    op.drop_table('read_category_projection')
    op.drop_index(op.f('ix_read_budget_projection_user_id'), table_name='read_budget_projection')
    op.drop_index('ix_read_budget_ledger_cat', table_name='read_budget_projection')
    op.drop_table('read_budget_projection')
    op.drop_index(op.f('ix_read_account_projection_user_id'), table_name='read_account_projection')
    op.drop_table('read_account_projection')
    op.drop_index(op.f('ix_backup_snapshots_user_id'), table_name='backup_snapshots')
    op.drop_index(op.f('ix_backup_snapshots_ledger_id'), table_name='backup_snapshots')
    op.drop_table('backup_snapshots')
    op.drop_index(op.f('ix_backup_artifacts_user_id'), table_name='backup_artifacts')
    op.drop_index(op.f('ix_backup_artifacts_ledger_id'), table_name='backup_artifacts')
    op.drop_index(op.f('ix_backup_artifacts_kind'), table_name='backup_artifacts')
    op.drop_index(op.f('ix_backup_artifacts_created_at'), table_name='backup_artifacts')
    op.drop_index(op.f('ix_backup_artifacts_checksum_sha256'), table_name='backup_artifacts')
    op.drop_index('idx_backup_artifacts_ledger_created', table_name='backup_artifacts')
    op.drop_table('backup_artifacts')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_ledger_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_attachment_files_user_id'), table_name='attachment_files')
    op.drop_index(op.f('ix_attachment_files_sha256'), table_name='attachment_files')
    op.drop_index(op.f('ix_attachment_files_ledger_id'), table_name='attachment_files')
    op.drop_index(op.f('ix_attachment_files_created_at'), table_name='attachment_files')
    op.drop_index('idx_attachment_files_sha256', table_name='attachment_files')
    op.drop_index('idx_attachment_files_ledger_created', table_name='attachment_files')
    op.drop_table('attachment_files')
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_sync_push_idempotency_user_id'), table_name='sync_push_idempotency')
    op.drop_index(op.f('ix_sync_push_idempotency_idempotency_key'), table_name='sync_push_idempotency')
    op.drop_index(op.f('ix_sync_push_idempotency_expires_at'), table_name='sync_push_idempotency')
    op.drop_index(op.f('ix_sync_push_idempotency_device_id'), table_name='sync_push_idempotency')
    op.drop_table('sync_push_idempotency')
    op.drop_index(op.f('ix_sync_cursors_user_id'), table_name='sync_cursors')
    op.drop_index(op.f('ix_sync_cursors_ledger_external_id'), table_name='sync_cursors')
    op.drop_index(op.f('ix_sync_cursors_device_id'), table_name='sync_cursors')
    op.drop_table('sync_cursors')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_device_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_ledgers_user_id'), table_name='ledgers')
    op.drop_index(op.f('ix_ledgers_external_id'), table_name='ledgers')
    op.drop_table('ledgers')
    op.drop_index(op.f('ix_devices_user_id'), table_name='devices')
    op.drop_index(op.f('ix_devices_revoked_at'), table_name='devices')
    op.drop_index(op.f('ix_devices_last_seen_at'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_users_is_enabled'), table_name='users')
    op.drop_index(op.f('ix_users_is_admin'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
